# 应用名称
spring:
  application:
    name: rocketmq-producer

# 端口
server:
  port: 8085

# rocket配置
rocketmq:
  #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
  #groupName: please_rename_unique_group_name
  #是否开启自动配置
  isEnable: true
  #mq的nameserver地址
  namesrvAddr: 47.115.45.141:10910
  #消息最大长度 默认1024*4(4M)
  producer:
    groupName: ${spring.application.name}
    #namesrvAddr: 1.116.189.73:9876
    maxMessageSize: 4096
  #发送消息超时时间,默认3000
    sendMsgTimeout: 3000
  #发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
  consumer:
    #namesrvAddr: 1.116.189.73:9876
    groupName: ${spring.application.name}
    #消费者线程数量
    consumeThreadMin: 5
    consumeThreadMax: 32
  #设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1