# 应用名称
spring:
  application:
    name: spring-email
  mail:
    host: smtp.126.com #发送邮件服务器
    username: youjinbo923@126.com #163邮箱账号
    password: ULISRIXIGTOKCDZQ #授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 994 #端口号465或994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.debug: true
    default-encoding: utf-8

# 端口
server:
  port: 8081
